path:
  ckpt_path: "./output/ckpt/M-AILABS+RN"
  log_path: "./output/log/M-AILABS+RN"
  result_path: "./output/result/M-AILABS+RN"
optimizer:
  batch_size: 48
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: []
  anneal_rate: 0.3
step:
  total_step: 70000
  log_step: 100
  synth_step: 400
  val_step: 400
  save_step: 1000
