initials = [
    "b",
    "c",
    "ch",
    "d",
    "f",
    "g",
    "h",
    "j",
    "k",
    "l",
    "m",
    "n",
    "p",
    "q",
    "r",
    "s",
    "sh",
    "t",
    "w",
    "x",
    "y",
    "z",
    "zh",
]
finals = ['S', 'Sj', 'StS', 'StSj', 'Z', 'Zj', 'a', 'b', 'bj', 'd', 'dj', 'e', 'f', 'g', 'hrd', 'i', 'i2', 'j', 'jA', 'jE', 'jO', 'jU', 'k', 'l', 'lj', 'm', 'mj', 'n', 'nj', 'o', 'p', 'pj', 'r', 'rj', 's', 'sj', 't', 'tS', 'tSj', 'tj', 'ts', 'u', 'v', 'vj', 'x', 'z', 'zj']
valid_symbols = initials + finals + ["rr"]
